export const dictionaries = {
  es: {
    orderNow: "Pedir ahora", admin: "Admin",
    heroKicker: "Pasteleria personalizada \u00b7 pedidos en linea",
    heroTitle: "Tu kake, exactamente como lo sonaste.",
    heroLead: "Elige tamano, sabor, relleno y diseno. Cada opcion suma al precio al instante.",
    customize: "Personalizar mi pedido", instagram: "Ver inspiracion en Instagram",
    cards: [{ t: "Tamano y porciones", d: "Paso a paso, con vista previa y precio en vivo." }, { t: "Sabores y rellenos", d: "Chocolate, vainilla, coco, fresa y dulce de leche." }, { t: "Diseno a tu gusto", d: "Elige del banco kake o sube tu referencia." }, { t: "Envio o recogida", d: "Domicilio o recogida en tienda." }],
    cakeAlt: "Pastel kake", wizardTitle: "Arma tu kake", wizardNote: "Cada paso es una pantalla.", continue: "Continuar personalizacion", stepOf: "Paso {n} de {total}",
    steps: { cliente: "Tus datos", fecha: "Fecha de entrega", hora: "Hora de entrega", envio: "Envio o recogida", size: "Tamano", sabor: "Sabor del pastel", relleno: "Sabor del relleno", capas: "Cantidad de rellenos", diseno: "Diseno favorito", resumen: "Confirmar pedido" },
    name: "Nombre", phone: "Telefono", email: "Email", addressOptional: "Direccion (opcional)", dateLabel: "Fecha de entrega (manana por defecto)", timeLabel: "Hora de entrega", shipAddress: "Direccion de envio", pickupHint: "Si eliges recogida, pasa al siguiente paso.", designHint: "Elige del banco kake o sube tu referencia.", orUrl: "O pega la URL de tu imagen", ownDesign: "Diseno propio", confirm: "Confirmar y guardar pedido", back: "Atras", next: "Siguiente", saving: "Guardando...", saved: "Pedido {n} confirmado!", saveError: "Error al guardar", needClient: "Completa nombre, telefono y email.", needAddress: "Escribe la direccion de envio.", measure: "Medida", flavor: "Sabor", filling: "Relleno", layers: "Capas", design: "Diseno", delivery: "Entrega", fillingWord: "relleno", own: "propio", adminTitle: "Panel admin kake", adminKeyHint: "Clave por defecto: kake", adminKey: "Clave admin", enter: "Entrar", loaded: "Catalogo y pedidos cargados", badKey: "Clave incorrecta", addOption: "Agregar / editar opcion", label: "Etiqueta", description: "Descripcion", price: "Precio", sampleUrl: "URL imagen", saveOption: "Guardar opcion", optionSaved: "Opcion guardada", category: "Categoria", option: "Opcion", photoBank: "Banco de fotos", designName: "Nombre del diseno", photoUrl: "URL de foto", extraPrice: "Precio extra", addBank: "Agregar al banco", designAdded: "Diseno agregado", orders: "Pedidos", orderNum: "# Pedido", customerId: "ID cliente",
    cats: { size: "Tamano", cake_flavor: "Sabor pastel", filling: "Sabor relleno", filling_count: "Cantidad rellenos", delivery: "Envio / recogida" },
    labels: { "6 pulgadas (8-12 porciones)": "6 pulgadas (8-12 porciones)", "8 pulgadas (15-20 porciones)": "8 pulgadas (15-20 porciones)", "10 pulgadas (25-32 porciones)": "10 pulgadas (25-32 porciones)", Chocolate: "Chocolate", Vainilla: "Vainilla", Coco: "Coco", Fresa: "Fresa", "Dulce de leche": "Dulce de leche", "2 rellenos": "2 rellenos", "3 rellenos": "3 rellenos", "Envio a domicilio": "Envio a domicilio", "Recogida en tienda": "Recogida en tienda" }
  },
  en: {
    orderNow: "Order now", admin: "Admin", heroKicker: "Custom bakery \u00b7 order online", heroTitle: "Your kake, exactly as you imagined it.", heroLead: "Pick size, flavor, filling and design. Each choice adds to the live total.", customize: "Customize my order", instagram: "See inspiration on Instagram",
    cards: [{ t: "Size and servings", d: "Step by step, with live preview and price." }, { t: "Flavors and fillings", d: "Chocolate, vanilla, coconut, strawberry and dulce de leche." }, { t: "Your design", d: "Pick from the kake gallery or upload a reference." }, { t: "Delivery or pickup", d: "Home delivery or store pickup." }],
    cakeAlt: "kake cake", wizardTitle: "Build your kake", wizardNote: "Each step is its own screen.", continue: "Continue customizing", stepOf: "Step {n} of {total}",
    steps: { cliente: "Your details", fecha: "Delivery date", hora: "Delivery time", envio: "Delivery or pickup", size: "Size", sabor: "Cake flavor", relleno: "Filling flavor", capas: "Number of fillings", diseno: "Favorite design", resumen: "Confirm order" },
    name: "Name", phone: "Phone", email: "Email", addressOptional: "Address (optional)", dateLabel: "Delivery date (default tomorrow)", timeLabel: "Delivery time", shipAddress: "Delivery address", pickupHint: "If you choose pickup, go to the next step.", designHint: "Pick from the kake gallery or add your reference.", orUrl: "Or paste your image URL", ownDesign: "Custom design", confirm: "Confirm and save order", back: "Back", next: "Next", saving: "Saving...", saved: "Order {n} confirmed!", saveError: "Could not save", needClient: "Please fill in name, phone and email.", needAddress: "Enter the delivery address.", measure: "Size", flavor: "Flavor", filling: "Filling", layers: "Layers", design: "Design", delivery: "Delivery", fillingWord: "filling", own: "custom", adminTitle: "kake admin", adminKeyHint: "Default key: kake", adminKey: "Admin key", enter: "Enter", loaded: "Catalog and orders loaded", badKey: "Wrong key", addOption: "Add / edit option", label: "Label", description: "Description", price: "Price", sampleUrl: "Image URL", saveOption: "Save option", optionSaved: "Option saved", category: "Category", option: "Option", photoBank: "Photo bank", designName: "Design name", photoUrl: "Photo URL", extraPrice: "Extra price", addBank: "Add to gallery", designAdded: "Design added", orders: "Orders", orderNum: "Order #", customerId: "Customer ID",
    cats: { size: "Size", cake_flavor: "Cake flavor", filling: "Filling flavor", filling_count: "Filling count", delivery: "Delivery / pickup" },
    labels: { "6 pulgadas (8-12 porciones)": "6 inches (8-12 servings)", "8 pulgadas (15-20 porciones)": "8 inches (15-20 servings)", "10 pulgadas (25-32 porciones)": "10 inches (25-32 servings)", Chocolate: "Chocolate", Vainilla: "Vanilla", Coco: "Coconut", Fresa: "Strawberry", "Dulce de leche": "Dulce de leche", "2 rellenos": "2 fillings", "3 rellenos": "3 fillings", "Envio a domicilio": "Home delivery", "Recogida en tienda": "Store pickup" }
  }
};
export function translateLabel(lang, label) {
  if (!label) return label;
  return dictionaries[lang]?.labels?.[label] || label;
}
